### ISSUE TITLE
PrintManagementDsc throws an error during build

### ISSUE THREAD

**Issue by KosherSalt** [puppetlabs/Puppet.Dsc#113]
## Describe the Bug

This line is throwing an error during the build process
https://github.com/limiteddenial/PrintManagementDsc/blob/master/PrintManagementDsc.psd1#L54

```
Test-ModuleManifest : The specified RequiredModules entry 'PrintManagement' in the module manifest
'C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc\PrintManagementDsc.psd1' is
invalid. Try again after updating this entry with valid values.
At line:31 char:5
+     Invoke-DscResource @InvokeParams
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\temp\dsc_2_p...agementDsc.psd1:String) [Test-ModuleManifest], Direct
   oryNotFoundException
    + FullyQualifiedErrorId : Modules_InvalidRequiredModulesinModuleManifest,Microsoft.PowerShell.Commands.TestModuleM
   anifestCommand

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to
Stop: The specified RequiredModules entry 'PrintManagement' in the module manifest
'C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc\PrintManagementDsc.psd1' is
invalid. Try again after updating this entry with valid values.
```

## Expected Behavior
Expected the module to build to a puppet module

## Steps to Reproduce
New-PuppetDscModule -PowerShellModuleName 'PrintManagementDsc' -PowerShellModuleVersion '2.0.0' -PuppetModuleAuthor 'testuser' -OutputDirectory '.' 

## Environment
powershellget 2.2.5
windows 2019
powershell 5.1

**Comment by jpogran** [comment]
@KosherSalt Are you running the builder on a machine that has the `PrintManagement` module installed? The `RequireModules` setting requires the module to be present before allowing PowerShell to import the parent module, and IIRC the builder imports the DSC Resource in order to parse it. This means to be it would need to be present for this to succeed.

**Comment by KosherSalt** [comment]
Yeah, the machine has PrintManagement installed. It looks like that module is installed by default from what I can tell
(https://docs.microsoft.com/en-us/powershell/module/printmanagement/?view=win10-ps)

**Comment by michaeltlombardi** [comment]
This dependency module _should_ be downloaded and vendored in with the DSC module in question - we'll look to validate this when I can and see if I can repro locally and figure out what's going on.

**Comment by KosherSalt** [comment]
One thing to note is that the required module isn't on PowerShellGallery, it's already included on the system by default I believe.

From some testing, I'm assuming that what's happening is that since the PsModulePath is being overwritten, the Test-ModuleManifest can't find the local ones

To test, I pasted the Set-PSModulePath into a new powershell window and got the values before and after running the function. Running test-modulemanifest before running these worked, but failed after.

```
PS C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc> $env:PSModulePath
C:\Users\username\Documents\WindowsPowerShell\Modules;C:\Program Files (x86)\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

```
PS C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc> $VendoredDscResourcesDirectory =  "c:/temp/dsc_2_puppet/printmanagementdsc/lib/puppet_x/dsc_resources"
>>
>> Set-PSModulePath -Path $VendoredDscResourcesDirectory
```

```
PS C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc> $env:PSModulePath
c:/temp/dsc_2_puppet/printmanagementdsc/lib/puppet_x/dsc_resources
```

After setting the PSModulePath like it's being done in New-PuppetDscModule and Set-PSModulePath, the Test-ModuleManifest can't find the module like the error I've seen
```
PS C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc> Test-ModuleManifest .\PrintManagementDsc.psd1
Test-ModuleManifest : The specified RequiredModules entry 'PrintManagement' in the module manifest
'C:\temp\dsc_2_puppet\printmanagementdsc\lib\puppet_x\dsc_resources\PrintManagementDsc\PrintManagementDsc.psd1' is
invalid. Try again after updating this entry with valid values.
At line:1 char:1
+ Test-ModuleManifest .\PrintManagementDsc.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\PrintManagementDsc.psd1:String) [Test-ModuleManifest], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : Modules_InvalidRequiredModulesinModuleManifest,Microsoft.PowerShell.Commands.TestModuleM
   anifestCommand


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.0.0.0    PrintManagementDsc

```

**Comment by KosherSalt** [comment]
I saw the Set-PsModulePath accepted a string array, so I locally changed the it in new-puppetdscmodule to include the old path as well. This seems to work as the build ran without failures. I'm not sure how this affects other build types or processes, but it's serving as a workaround at the very least until more testing can be done.

https://github.com/puppetlabs/Puppet.Dsc/blob/main/src/functions/New-PuppetDscModule.ps1#L130

`        Set-PSModulePath -Path ($VendoredDscResourcesDirectory, $env:psmodulepath)`
