### ISSUE TITLE
Replace deprecated xDefender module with WindowsDefender

### ISSUE THREAD

**Issue by brajjan** [puppetlabs/Puppet.Dsc#143]
As stated in https://github.com/dsccommunity/xDefender the xDefender module is deprecated and should be replaced with the WindowsDefender DSC-module https://www.powershellgallery.com/packages/WindowsDefender/ or at least build the WindowsDefender module and publish it to puppet forge

**Comment by michaeltlombardi** [comment]
@brajjan we're going to leave the deprecated module up (and rebuild those versions as needed) so folks depending on the old versions can still use them, but I've gone ahead and [made the WindowsDefender module available on the Forge too with all extant versions](https://forge.puppet.com/modules/dsc/windowsdefender).
