### ISSUE TITLE
Autogenerated Module Readme does not include the PowerShell or Puppet Module Names

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#153]
## Describe the Bug
The autogenerated module readmes should include:

- the Puppet Module name as the first level header
- The PowerShell module name and link to the module in several places (link depends on the name)

This is because `New-PuppetDscModule` calls `Update-PuppetModuleReadme` without passing either the `$PowerShellModuleName` or `$PuppetModuleName` parameters: https://github.com/puppetlabs/Puppet.Dsc/blob/99a9e99295377e89a363b5ada593e5d27515ba4e/src/functions/New-PuppetDscModule.ps1#L139

Those values need to be passed to `Update-PuppetModuleReadme` as that function uses them when calling `Get-ReadmeContent`: https://github.com/puppetlabs/Puppet.Dsc/blob/99a9e99295377e89a363b5ada593e5d27515ba4e/src/internal/functions/Update-PuppetModuleReadme.ps1#L47-L55

Where they are then used several times:

- https://github.com/puppetlabs/Puppet.Dsc/blob/99a9e99295377e89a363b5ada593e5d27515ba4e/src/internal/functions/Get-ReadmeContent.ps1#L59
- https://github.com/puppetlabs/Puppet.Dsc/blob/99a9e99295377e89a363b5ada593e5d27515ba4e/src/internal/functions/Get-ReadmeContent.ps1#L70
- https://github.com/puppetlabs/Puppet.Dsc/blob/99a9e99295377e89a363b5ada593e5d27515ba4e/src/internal/functions/Get-ReadmeContent.ps1#L71

## Acceptance Criteria

- [x] The call to `Update-PuppetModuleReadme` in `New-PuppetDscModule` includes the missing parameters
- [x] All of the parameters in `Update-PuppetModuleReadme` are marked as mandatory and validation prevents passing null or empty values
  - convert from `[string]` to `[Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()][String]`
- [x] Additional unit tests for when `Update-PuppetModuleReadme` is passed null and empty string values
- [x] The `$PowerShellModuleName` and `$PuppetModuleName` parameters in `Get-ReadmeContent` are marked as mandatory and validation prevents passing null or empty values for any parameter
  - convert from `[string]` to `[Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()][String]`
- [x] Additional unit tests for when `Get-ReadmeContent` is passed null and empty string values for `$PowerShellModuleName` and `$PuppetModuleName`
- Changelog `Fixed` Entries:
  - [x] Entry clarifying fixes for auto-generated readmes
  - [x] Entry clarifying improved UX to prevent failed behavior when passing null/empty strings to `Update-PuppetModuleReadme`
  - [x] Entry clarifying improved UX to prevent failed behavior when passing null/empty strings to `Get-ReadmeContent`

**Comment by david22swan** [comment]
In regards to the setting of `$PuppetModuleName` as mandatory, have decided to forgo this as code exists to use the `$PowerShellModuleName` in it's place if it was not given.
