### ISSUE TITLE
Make `Publish-NewDscModuleVersion` publish new versions from oldest to newest

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#197]
## Use Case
If a call to `Publish-NewDscModuleVersion` is cancelled for any reason mid-run (error, timeout, etc) because it builds from newest-to-oldest unpublished versions, you can no longer use the `OnlyNewer` flag to prevent building published versions older than what is on the Forge _and_ can end up in a state where several old versions are Puppetized, then only the newest version is Puppetized, leaving a several-version wide gap.

## Describe the Solution You Would Like
`Publish-NewDscModuleVersion` sorts the versions to Puppetize by oldest to newest before attempting to Puppetize each in turn.

**Comment by jordanbreen28** [comment]
Closing as electing to raise on Jira
