### ISSUE TITLE
Repuppetize Modules Workflow

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#200]
Add a GHA workflow of for Puppetizing PowerShell modules with DSC Resources which:
- [ ] Runs on tagged release of Puppet.Dsc
- [ ] Rebuilds the latest 5 versions of every Puppetized DSC module on the forge, publishing the modules with an incremented build version
- [ ] Builds the matrix for Puppetization of modules dynamically

**Comment by jordanbreen28** [comment]
Closing as work completed - https://github.com/puppetlabs/Puppet.Dsc/actions/workflows/repuppetize.yml
