### ISSUE TITLE
[dsc-dfsdsc] Enum lowercase mismatch

### ISSUE THREAD

**Issue by ShopenBouber** [puppetlabs/Puppet.Dsc#211]
## Describe the Bug
When using class for namespaceroot and folder creation (dsc_dfsnamespaceroot, dsc_dfsnamespacefolder).
When letting the default value for dsc_referralpriorityclass got a warning from dsc provider : 

```
Warning: Provider returned data that does not match the Type Schema for `dsc_dfsnamespacefolder[my_folder]`

Value type mismatch:

    * dsc_referralpriorityclass: sitecost-normal (expects an undef value or a match for Enum['Global-High', 'Global-Low', 'SiteCost-High', 'SiteCost-Low', 'SiteCost-Normal'], got 'sitecost-normal')
```

Seems like the puppet module are awaiting for a camel case string match, where the windows system had a lowercase value.
I tried to explicitly declare value for this param but the Enum from the autogenerated ressource doesn't accept it (legitimately)
I also tried to change the validation_mode to ressource instead of property => same 

## Expected Behavior

Actually, for now, the ressource are properly created on system side, but puppet alway get a wrong string value generating a warning on every run.

## Steps to Reproduce

Declare in puppet dfs namespace root and folders with theses ressources from dsc-dfsdsc autogenerated module : 
dsc_dfsnamespaceroot
dsc_dfsnamespacefolder

## Environment
 - Version: 10.0.17763
 - Platform: Windows Server 2019 Build 

## Additional Context

I'm not sure if this Enum problem comes from puppet autogenerated module or the DSC module.
I'm a beginner in puppet and especially with DSC ressources, but here's what I found : 

- Concerned files on puppet side  : 
lib\puppet\type\dsc_dfsnamespaceroot.rb  line 70-73
lib\puppet\type\dsc_dfsnamespacefolder..rb line 70-73
```
dsc_referralpriorityclass: {
    type: "Optional[Enum['Global-High', 'SiteCost-High', 'SiteCost-Normal', 'SiteCost-Low', 'Global-Low']]",
    desc: 'Specifies the target priority class for a DFS namespace root.',
```

- On the DSC Side : 
Found the same string case on DSC ressources  line 230 on lib\puppet_x\dfsdsc\dsc_resources\DFSDsc\DSCResources\MSFT_DFSNamespaceRoot\MSFT_DFSNamespaceRoot.psm1 : 
```
        [Parameter()]
        [ValidateSet('Global-High','SiteCost-High','SiteCost-Normal','SiteCost-Low','Global-Low')]
        [System.String]
        $ReferralPriorityClass,
```

- Powershell ressource called : 
But on the powershell cmdlet for dfsroot namespace creation we have : 
```
Type:	ReferralPriorityClass
Aliases:	PriorityClass, Class
Accepted values:	sitecostnormal, globalhigh, sitecosthigh, sitecostlow, globallow
```
(founded on https://docs.microsoft.com/en-us/powershell/module/dfsn/new-dfsnroottarget?view=windowsserver2022-ps)

Seems like a DSC ressource issue but i'm not totally sure because of my lack of experience, i'm available if you need further informations.
I checked issues on DFS DSC repo and this issue seems proper to call the DSC ressource through puppet
I'll try to apply the DSC ressource from puppet agent debug directly to provide more test informations.

Sorry if this issue has nothing to do here.

Thank's in advance for you answer

**Comment by chelnak** [comment]
Hey @ShopenBouber, Thanks for letting us know about this. It's certainly an interesting one. I'll set up a lab next week and see if i can replicate. In the meantime it would be great if you could share a (redacted) manifest with us. Just so we can see how you are using the resource and to ensure we are testing the right thing!

Have a great weekend!

**Comment by ShopenBouber** [comment]
Hello,
Thanks for your answer, here's a manifest example : 
```
class win_shares::dfsroot_config (
){
  dsc_dfsnamespaceroot { 'namespace_test':
    dsc_ensure                      => Present,
    dsc_type                         => 'DomainV2',
    dsc_path                         => '\\domain.local\test',
    dsc_targetpath                => '\\hostname.domain.local\test',
    dsc_description                => 'Puppet-Managed NamespaceRoot',
    dsc_psdscrunascredential => {
      'user'     => 'svc_puppet',
      'password' => Sensitive($svc_puppet_password),
    },
  }
}
```
I usually use this in a define to call it with a create ressource and use hieradata as input, but, to simplified as much a possible, the example below has been tested and it result the same (with the value type mismatch for dsc_referralpriorityclass

**Comment by ShopenBouber** [comment]
Hello,
Any news about this please ?

**Comment by chelnak** [comment]
Hey @ShopenBouber, I just took a look at this. 

From what I can tell the warning is being generated because the DSC resource returns values that do not match the values  expected from the `ValidateSet` of `$ReferralPriorityClass`.

The DSC resource expects the values to be `CamelCase` for `$ReferralPriorityClass`.

When the state of the system is gathered, `Get-DfsnFolderTarget` is called, which will return [lowercase values](https://docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=windowsserver2022-ps#example-1-get-settings-for-a-target) back to DSC. 

This is where the mismatch is occurring.

Puppet generates types from the definition of the DSC resource. Therefore takes the values specified in the `ValidateSet` for $ReferralPriorityClass and expects an exact case sensitive match.

Hope that makes sense?

A possible solution would be to fix the DFS DSC resource so that the expected values match what will be returned by the DFS cmdlets.

Thanks!
