### ISSUE TITLE
[SqlServerDsc] Improper type for ipaddress on dsc_sqlaglistener

### ISSUE THREAD

**Issue by cummingscody** [puppetlabs/Puppet.Dsc#215]
## Describe the Bug
```
dsc_sqlaglistener{ 'AvailabilityGroupListener':
  dsc_ensure => 'Present',
  dsc_servername => $fqdn,
  dsc_instancename => 'MSSQLSERVER',
  dsc_availabilitygroup => $sqlserveralwayson::clustername,
  dsc_name => "${sqlserveralwayson::clustername}-AGL",
  dsc_ipaddress => $sqlserveralwayson::listener_ip,
  dsc_port => 1433,
  validation_mode => 'resource',
  dsc_psdscrunascredential => {
    'user' => $sqlserveralwayson::domain_admin_username,
    'password' => Sensitive($sqlserveralwayson::domain_admin_password)
  },
  require => [ Dsc_sqlag['CreateSQLAvailabilityGroup'] ]
}
```
```
Debug: dsc_sqlaglistener: Canonicalized Resources: [{:dsc_availabilitygroup=>"test", :dsc_ensure=>"Present", :dsc_instancename=>"MSSQLSERVER", :dsc_ipaddress=>"172.24.200.253", :dsc_name=>"test-AGL", :dsc_port=>1433, :dsc_servername=>"alwayson-e1.pilot.usda.lab", :name=>"AvailabilityGroupListener", :validation_mode=>"resource", :dsc_psdscrunascredential=>{"user"=>"pilot\\SVC_Mgmt_Join_AD", "password"=>#<Sensitive [value redacted]>}}]
```
It looks like Puppets type and provider is expecting an array or undef but the resources spit out a string for ipaddress.

## Expected Behavior
The code should properly execute instead of `Error: Failed to apply catalog: Parameter dsc_ipaddress failed on Dsc_sqlaglistener[AvailabilityGroupListener]: dsc_sqlaglistener.dsc_ipaddress expects a value of type Undef or Array, got String`

## Environment
Module Version: curr(15.2.0)
Puppet Version: PE 2021.5, Agent UNKNOWN
OS Name/Version: Windows, Server 2019

**Comment by LukasAud** [comment]
After some investigation, it was concluded that the DSC module is converting the resource into an appropriate puppet type (according to PowerShell documentation). 

However, it is noted that PowerShell allows certain practices, such as providing Strings as valid values for String[], which are not supported by puppet code. An example of this can be found in some GitHub DSC repos such as: https://github.com/dsccommunity/SqlServerDsc/wiki/SqlAGListener#examples 

This may cause some confusion to users, so it was decided to add a new section to our documentation to warn users of this potential problem. This documentation update can be found at #220.

**Comment by LukasAud** [comment]
As per #220 merge, we will be considering this issue resolved and closing it. Thanks for your report!
