### ISSUE TITLE
REAMDE is missing link to original puppetlabs/dsc module in limitations section

### ISSUE THREAD

**Issue by binford2k** [puppetlabs/Puppet.Dsc#217]
The README page renders an empty link for this https://github.com/puppetlabs/Puppet.Dsc/blob/42927dc2f285c7e0430d90a690034849636ac6c8/src/internal/functions/Get-ReadmeContent.ps1#L154, which makes me think that the `$LegacyDscForgePage` variable isn't set properly.

See https://forge.puppet.com/modules/dsc/computermanagementdsc#known-limitations for an example.

**Comment by LukasAud** [comment]
Hey @binford2k, it seems that this issue was addressed and solved some time ago. Can we close it?

**Comment by chelnak** [comment]
Closing as complete. I've just generated a new module with the latest release and the link in the readme has been set properly.
