### ISSUE TITLE
[NetworkingDsc] Not available in most recent version via forge.puppet.com

### ISSUE THREAD

**Issue by norbertstoll** [puppetlabs/Puppet.Dsc#218]
Hi.

(I didn't really know where to put this question, so I'm trying it over here. Sorry if I'm wrong and someone knows a better place to ask.)

On may 30th a new stable version v9.0.0 of [networkingdsc](https://github.com/dsccommunity/NetworkingDsc/releases/tag/v9.0.0) has been released. Until today it's not available via [forge](https://forge.puppet.com/modules/dsc/networkingdsc).

I thought there might be an automatism, which is puppetizing those modules and offering the modules afterwards. Seems like I was wrong. So my question is, when it's going to be published since we are already waiting impatiently because it contains a bug fix 😃

Regards

**Comment by chelnak** [comment]
Hey @norbertstoll,

The automated conversion is on a time-out right now. We can look at getting the updated version of `networkingdsc` published for you in the meantime.

**Comment by chelnak** [comment]
Hello @norbertstoll ! v9 of networkingdsc is now available on the [forge](https://forge.puppet.com/modules/dsc/networkingdsc).

**Comment by norbertstoll** [comment]
Thanks a lot @chelnak! 🥳
