### ISSUE TITLE
fsrmdsc PowerShell Gallery module fails on Windows Server 2016 but is successful on Windows 2019

### ISSUE THREAD

**Issue by aaronhilton0** [puppetlabs/Puppet.Dsc#223]
## Describe the Bug
Customer is pulling ransomware_patterns from `https://fsrm.experiant.ca/api/v1/combined` which is large and contains unicode characters. When running `https://forge.puppet.com/modules/dsc/fsrmdsc` on a Windows 2019 node, all works as expected with the FSRM File Group being created and maintained properly. On Windows 2016, the module fails with the message `Could not evaluate: ReportEventW failed to report event to Windows eventlog:  A device attached to the system is not functioning.`

Running the fsrmdsc module directly through Powershell with the same patterns for the DSRMFileGroup include pattern, the configuration completes successfully on both Win 2019 and Win 2016.

## Expected Behavior
The module should work properly on both Windows 2019 and Windows 2016

## Steps to Reproduce
I have attached  [afsrmdsc.zip](https://github.com/puppetlabs/Puppet.Dsc/files/9428083/afsrmdsc.zip) which is the test module I wrote based on code the customer shared which exhibits the problem. This module does not manage the Windows "File Server Resource Manager" feature which will need to be installed prior to using this module. 

## Environment
 - dsc/fsrmdsc version 2.5.0-0-4
 - puppetlabs/stdlib versions 6.5.0, 7.0.0 and 8.4.0
 - Windows Server 2016 Datacenter build 14393.5291

## Additional Context
Attaching [dscbug.log](https://github.com/puppetlabs/Puppet.Dsc/files/9428221/dscbug.log) which is a debug agent run from an affected Windows 2016 server.

**Comment by chelnak** [comment]
@aaronhilton0 I'm going to take a look at this.

I'll update as soon as I have relevant info

**Comment by jordanbreen28** [comment]
Hey @aaronhilton0 - I'll go ahead and close this.
please re-open if the issue still persists
