### ISSUE TITLE
dsc_aduser and password (Sensitive[String]) preventing action

### ISSUE THREAD

**Issue by ernstae** [puppetlabs/Puppet.Dsc#227]
## Describe the Bug
I'm using the latest version of the puppetlabs-pwshlib library in an attempt to add an active directory user. 

## Expected Behavior
The expected result is to have puppet generate the necessary DSC hand-off and implement the creation of the user.
Instead, I'm being presented with the error message that was introduced in puppetlabs/ruby-pwsh#150 

```
        Error: dsc_aduser[{:name=>"SQL Server User crappyfoo1", :dsc_username=>"crappyfoo1", :dsc_domainname=>"domainname.com"}]: Creating: Failed after 0.003257 seconds: Unredacted sensitive data would've been leaked
        Error: /Stage[main]/Domain_controller/Domain_controller::Service_account[crappyfoo]/Dsc_aduser[SQL Server User crappyfoo1]: Could not evaluate: Execution encountered an error
```

## Steps to Reproduce

Sample code:

```puppet
$ensure = true

dsc_aduser { "SQL User crappyfoo1":
  dsc_username             => 'crappyfoo',
  dsc_cannotchangepassword => true,
  dsc_displayname          => 'SQL User crappyfoo',
  dsc_domainname           => 'domainname.com',
  dsc_ensure               => bool2str($ensure, 'Present', 'Absent'),
  dsc_path                 => $svcAccountsPath, 
  dsc_password             => { user => $login, password => Sensitive($password)},
}
```

## Environment
 - version:   "version": "0.10.1", puppetlabs-pwshlib
 - version: mod 'dsc-activedirectorydsc', '6.0.1-0-4'

**Comment by chelnak** [comment]
Hello, it looks like we've not had a response in some time. I'm going to close this issue but if it is still relevant please feel free to reply with the information that has been requested previously.

Thank you!
