### ISSUE TITLE
Incorrect Casing of Subproperty in xwebadministration

### ISSUE THREAD

**Issue by cummingscody** [puppetlabs/Puppet.Dsc#229]
## Describe the Bug
Forge Module: xwebadministration
Resource: dsc_xwebsite
Property: dsc_bindinginfo

Subproperty certificatestorename accepts either 'My', or 'WebHosting'
-'My' should be 'MY'

dsc_xwebadministration module on the PowerShell Gallery defaults have:
CertificateStoreName = 'MY'

## Expected Behavior
Update dsc_xwebsite > dsc_bindinginfo > certificatestorename => Optional[Enum['My'] TO 'MY' to resolve this issue.

## Environment
- Module
'dsc-xwebadministration', '3.3.0-0-0'
 - Platform 
 Server 2019

## Additional Context
This displays a warning of 
```
Warning: Provider returned data that does not match the Type Schema for `dsc_xwebsite[xxxx]
  Value type mismatch:
 index 0 entry `certificatestorename` expects an undef value or a match for Enum['My', 'WebHosting'], got 'MY'
 ```

**Comment by pmcmaw** [comment]
Closing in favor of internal tracking: https://tickets.puppetlabs.com/browse/CONT-206
