### ISSUE TITLE
Resource parameter Enum type is not generated correctly

### ISSUE THREAD

**Issue by ShawnHardwick** [puppetlabs/Puppet.Dsc#240]
## Describe the Bug
When using the `dsc_timezone` resource in dsc-computermanagementdsc (version 8.5.0-0-1) with the `dsc_issingleinstance` parameter, the Puppet catalog fails with the below log error:
>Could not retrieve catalog from remote server: 
Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/dsc_timezone: The type of the `dsc_issingleinstance` attribute `Enum['Yes''yes']` could not be parsed: Syntax error at 'yes' (line: 1, column: 11) (file: /opt/puppetlabs/server/data/puppetserver/filesync/client/versioned-dirs/puppet-code/winprov_dsc_transition_9277c53136bb5950344b94fb072c833447ad0f63/modules/win/manifests/timezone.pp, line: 9, column: 3) on node server1.domain1.com

Upon review of the `dsc-computermanagementdsc` generated Puppet module, it appears that the parameter type for `dsc_issingleinstance` is not generated correctly:
```
    dsc_issingleinstance: {
      type: "Enum['Yes''yes']",
      desc: "Specifies the resource is a single instance, the value must be 'Yes'.",
      behaviour: :namevar,
      mandatory_for_get: true,
      mandatory_for_set: true,
      mof_type: 'String',
      mof_is_embedded: false,
    }
```
The type value should be `"Enum['Yes', 'yes']"` (Note the comma)

Looking at the DSC resource schema MOF, the schema appears to be correct though I am not as familiar with this:
https://github.com/dsccommunity/ComputerManagementDsc/blob/main/source/DSCResources/DSC_TimeZone/DSC_TimeZone.schema.mof

## Expected Behavior
No catalog failure. `dsc_issingleinstance` should support "Yes" or "yes" as values.

## Steps to Reproduce
Apply the below resource using `dsc-computermanagementdsc` version 8.5.0-0-1:
```
  dsc_timezone { "Tonga Standard Time":
    dsc_timezone         => "Tonga Standard Time",
    dsc_issingleinstance => 'yes',
  }
```
## Notes
This appears to also affect the `dsc_issingleinstance` parameter in the `dsc_remotedesktopadmin` resource in the same module as well.

**Comment by chelnak** [comment]
Hey @ShawnHardwick 

This should be fixed in main. Feel free to take it for a test drive.

I'll work on getting a release out soon.

Cheers!

**Comment by ShawnHardwick** [comment]
Thanks for the quick fix. Unfortunately this will require a regeneration of the Puppet forge modules. I've already fixed this internally by forking.

**Comment by jordanbreen28** [comment]
Hi @ShawnHardwick - I'm electing to close this issue as the problem should be resolved with the next module generation. 
If you find the problem to persist, we will pick it back up from here ASAP.
Thanks for raising this one!

**Comment by chelnak** [comment]
@ShawnHardwick - This has been released and a new version of the module should now be on the Forge.
