### ISSUE TITLE
Re-Puppetize - dsc-computermanagementdsc

### ISSUE THREAD

**Issue by workjaf** [puppetlabs/Puppet.Dsc#245]
## DSC Resource name

* Name: mod 'dsc-computermanagementdsc', '8.5.0-0-1'

## Why do you want us to Re-Puppetize this module?

As far as I can tell, every puppetized DSC resource that contains "dsc_issingleinstance" is broken. They generate an enum as follows in the ruby file:
type: "Enum['Yes''yes']",
I believe it should be auto-generating a comma between these 2 values IE: "Enum['Yes','yes']. 

As a result, the following error is generated at run time:
Error: Could not autoload puppet/type/dsc_timezone: The type of the `dsc_issingleinstance` attribute `Enum['Yes''yes']` could not be parsed: Syntax error at 'yes' (line: 1, column: 11)
Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/dsc_timezone: The type of the `dsc_issingleinstance` attribute `Enum['Yes''yes']` could not be parsed: Syntax error at 'yes'

**Comment by workjaf** [comment]
I guess this has already been solved by closed issue #240. Would love to see a new version pushed up all the same as the current version does not function as-is. Especially since dsc_issingleinstance is a required property on numerous dsc resources. Thanks.

**Comment by chelnak** [comment]
@workjaf - A new version should be up on the Forge now.
