### ISSUE TITLE
Re-Puppetize - SqlServerDsc

### ISSUE THREAD

**Issue by wimsimons** [puppetlabs/Puppet.Dsc#250]
## DSC Resource name

* Name: sqlserverdsc

## Why do you want us to Re-Puppetize this module?

I am installing MSSQL Server 2022 and would like to use compatibility level for SQL Server 2022 (major version 16).
The latest stable version on github is 16.3.1 and on the forge it is 16.0.0.

**Comment by jordanbreen28** [comment]
@wimsimons there should be a newly released version of sqlserverdsc available on the forge now.
I'll go ahead and close this, but do re-open if you hit any issues.
