### ISSUE TITLE
Re-Puppetize - dsc-accesscontroldsc / dsc_registryaccessentry does not work

### ISSUE THREAD

**Issue by wuptagrafft-hxgn** [puppetlabs/Puppet.Dsc#251]
## dsc_registryaccessentry

* Name: accesscontroldsc
* Version: 1.4.3-0-0

## Why do you want us to Re-Puppetize this module?

Problems with the type definition, where you can't specify a valid set of properties for the DSC resource.

I have tried every possible combination of properties for this resource and I am unable to get any combination to work. I have provided a couple of examples below.

If anyone is able to provide a working example, then I will gladly use it, but it appears that the reference documentation is either wrong, this resource is broken, or I have a misunderstanding of the resource and/or documention.

#### Example 1:
Here I attempted to follow the reference documentation for the resource as specified at: https://forge.puppet.com/modules/dsc/accesscontroldsc/reference#dsc_registryaccessentry

Resource Declaration:
```
dsc_registryaccessentry { 'TempTest_Dsc_RegistryAccessEntry':
  dsc_path              => 'HKLM:\SOFTWARE\Wow6432Node\MyCompany\Applications\TempTestKey',
  dsc_accesscontrollist => [
    {
      accesscontrolentry => [
        {
          accesscontroltype => 'Allow',
          rights            => ['FullControl'],
          inheritance       => 'This Key and Subkeys',
          ensure            => 'Present',
          cim_instance_type => 'AccessControlEntry',
        },
      ],
      principal          => "mydomainname\\${facts['hostname']}-SVC",
    },
  ],
  validation_mode       => 'resource',
}
```
Resulting Error:
```
Could not evaluate: undefined method `[]' for nil:NilClass
Source:	/Stage[main]/Profile::TestProfile/Dsc_registryaccessentry[TempTest_Dsc_RegistryAccessEntry]

dsc_registryaccessentry: Could not find mandatory property AccessControlList. Add this property and try again.
Source:	Puppet
```
#### Example 2:
Here I attempted to add an accesscontrollist key as the previous attempt was complaining that the property was missing. Based off the DSC documentation examples found here:
https://github.com/mcollera/AccessControlDsc/blob/Dev/Examples/RegistryAccessEntry_example.ps1
because of the error that was displayed in example 1 above.

Resource Declaration:
```
dsc_registryaccessentry { 'TempTest_Dsc_RegistryAccessEntry':
  dsc_path              => 'HKLM:\SOFTWARE\Wow6432Node\MyCompany\Applications\TempTestKey',
  dsc_accesscontrollist => [
    accesscontrollist   => {
      accesscontrolentry => [
        {
          accesscontroltype => 'Allow',
          rights            => ['FullControl'],
          inheritance       => 'This Key and Subkeys',
          ensure            => 'Present',
          cim_instance_type => 'AccessControlEntry',
        },
      ],
      principal          => "mydomainname\\${facts['hostname']}-SVC",
    },
  ],
  validation_mode       => 'resource',
}
```
Resulting Error:
```
Failed to apply catalog: Parameter dsc_accesscontrollist failed on Dsc_registryaccessentry[TempTest_Dsc_RegistryAccessEntry]: dsc_registryaccessentry.dsc_accesscontrollist index 0 expects a value for key 'accesscontrolentry'

dsc_registryaccessentry.dsc_accesscontrollist index 0 unrecognized key 'accesscontrollist'

Source:	Puppet
```

**Comment by GSPatton** [comment]
hi @wuptagrafft-hxgn, thanks for raising this. What version of puppet are you running? And what os are you this running on?

Thanks

**Comment by pmcmaw** [comment]
Hey @wuptagrafft-hxgn 

I am just writing as I have had a quick look and according to the documentation would it be possible to try this again and avoid including `accesscontrollist`. Detailed documentation and an example of usage can be found here: https://forge.puppet.com/modules/dsc/accesscontroldsc/reference#properties-4

**Comment by jordanbreen28** [comment]
hey @wuptagrafft-hxgn - closing inline with the above comment. Please re-open if the issue still persists.
