### ISSUE TITLE
Re-Puppetize - [MODULE NAME]

### ISSUE THREAD

**Issue by amandaharth** [puppetlabs/Puppet.Dsc#293]
## DSC Resource name

* Name: computermanagementdsc
* Forge module version: mod 'dsc-computermanagementdsc', '9.1.0-0-0'
* Forge URL: https://forge.puppet.com/modules/dsc/computermanagementdsc/

## Why do you want us to Re-Puppetize this module?

The type schema for the dsc_useraccountcontrol resource type doesn't match the data returned by its provider.
Example error:
```
Error: /Stage[main]/Profile::Windows::User_account_control/Dsc_useraccountcontrol[Configure User Account Control]: Could not evaluate: Provider returned data that does not match the Type Schema for `dsc_useraccountcontrol[Configure User Account Control]`
 Value type mismatch:
    * dsc_consentpromptbehavioradmin: 5 (expects an undef value or a match for Enum['0', '1', '2', '3', '4', '5'], got Integer)
    * dsc_consentpromptbehavioruser: 3 (expects an undef value or a match for Enum['0', '1', '3'], got Integer)
    * dsc_enableinstallerdetection: 1 (expects an undef value or a match for Enum['0', '1'], got Integer)
    * dsc_enablelua: 1 (expects an undef value or a match for Enum['0', '1'], got Integer)
    * dsc_enablevirtualization: 1 (expects an undef value or a match for Enum['0', '1'], got Integer)
    * dsc_promptonsecuredesktop: 1 (expects an undef value or a match for Enum['0', '1'], got Integer)
    * dsc_validateadmincodesignatures: 0 (expects an undef value or a match for Enum['0', '1'], got Integer)
```

**Comment by jordanbreen28** [comment]
thanks for raising this @amandaharth! I've published version 9.1.0-0-1 of dsc-computermanagementdsc. Please note this modules are no longer officially supported, so if the repuppetize does not fix the issue there might not be anything we can do on our end to fix this! We are absolutely willing to still accept PRs that fix dsc module bugs in Puppet.Dsc and ruby-pwsh.
