### ISSUE TITLE
Re-Puppetize - [xPSDesiredStateConfiguration]

### ISSUE THREAD

**Issue by Daymarvi** [puppetlabs/Puppet.Dsc#302]
## DSC Resource name

* Name: xPSDesiredStateConfiguration

## Why do you want us to Re-Puppetize this module?

There is a new release available in github : 9.2.0 : https://github.com/dsccommunity/xPSDesiredStateConfiguration/tags can you please release it in the forge ?

Thanks a lot

**Comment by jordanbreen28** [comment]
@Daymarvi dsc-xPSDesiredStateConfiguration is now available on the forge at v9.2.0-0-0

**Comment by Daymarvi** [comment]
Thanks a lot @jordanbreen28 , testing... :-)
