### ISSUE TITLE
End to End Testing: Server-Agent Model

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#61]
End to end testing currently only validates serverless Puppet scenarios; as most production uses will instead involve agents reporting to a server, end to end testing should include this mode as well.

## Acceptance Criteria

- New matrix entry for acceptance testing which validates built module behavior in a server-agent configuration, running on PRs and nightly in GitHub Actions
  - [x] Ensure that the PowerShellGet module at v2.2.3 is built
  - [x] Ensure that a puppet server and several windows machines (with PowerShell 5.1) are deployed
  - [ ] Ensure that the newly puppetized powershellget module is installed to the puppet server in the appropriate environment for the agents to use it
  - [ ] Ensure that each agent attempts to idempotently apply a known-good configuration (reuse from prior tests if possible), report test failure if the run fails or is not idempotent.
  - [ ] Tear down nodes used for testing

**Comment by david22swan** [comment]
Steps:
- Create module locally on the runner
- Install module onto server
- Apply tests on server targeted at agents

**Comment by david22swan** [comment]
Due to the previously known bug, i.e.  https://github.com/puppetlabs/pdk/issues/1083, we are unable to build the module locally.
As such the testing process is now:
- Provision build machine to run Puppet.Dsc
- Provision server machine
- Provision two agent machines
- Build module on build machine
- Transfer to server machine and install
- Run the tests against the server targeted at the agents
- - Keep tests to bare minimum, test connection only

**Comment by michaeltlombardi** [comment]
Pulled out of 1.0.0 as unnecessary given current risk profile and evidence (ie widespread use by enterprise customers imply server-agent functionality). Still a nice-to-have, but no longer a blocker/immediate need.

**Comment by david22swan** [comment]
Current state:
1. Bundle environment set up on need, necessary files contained within spec and moved into position by the script when they are needed, i.e. Gemfile/Rakefile/.fixtures.yml
2. Machines provisioned using hard coded bolt within the script.
3. Plans adapted from Adrians work on websphere_application_server integration testing have been moved into the provision module and are now called to setup the server and agents.
4. `powershellget` module is generated using code taken from acceptance test's, exported to a .tar file and then uploaded and installed onto the server.
5. `puppet agent -t` is an against the agent machines

Error's have been hit on the 5th step with the below being returned:
```
Failed on 34.127.94.196:
  The command failed with exit code 1
  puppet.bat : Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/dsc_psrepository: Could not autoload puppet/provider/dsc_psrepository/dsc_psrepository: no such file to load -- puppet/provider/dsc_base_provider/dsc_base_provider (file: /etc/puppetlabs/code/environments/production/manifests/test.pp, line: 2, column: 3) on node litmus-1cc273cfca2c56b5.c.ia-content.internal
      + CategoryInfo          : NotSpecified: (Error: C...nt.internal:String) [], RemoteException
      + FullyQualifiedErrorId : NativeCommandError
```

Unsure of source of issue, was still investigating at time of decision to set aside.

**Comment by michaeltlombardi** [comment]
Ah, it's likely because the `puppetlabs-pwshlib` module never made it onto the server - that's what the error indicates to me, anyway. It's a dependency we need to make sure to put in place.

**Comment by jordanbreen28** [comment]
Confirmed this work was parked.
