### ISSUE TITLE
Add repeatable proccess for releasing the Puppet.Dsc module

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#67]
## Use Case
Releases are currently done entirely manually, which is error prone and slow. A repeatable, documented process which enables automated or nearly-automated releases is preferable.

## Acceptance Criteria

- [ ] A GitHub action workflow for Release is added which:
  - [ ] Runs on tagged release of the repository
  - [ ] Executes the full test suite
  - [ ] If all tests successful, builds and published Puppet.Dsc to the PowerShell gallery

**Comment by jordanbreen28** [comment]
Closing as work completed
