### ISSUE TITLE
Auto-Puppetize modules via GHA

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#69]
It would be useful to have a nightly process which searches the PowerShell gallery for new releases of modules with DSC Resources and then Puppetizes and publishes those newly released modules to the Forge. This would ensure that the autogenerated modules on the Forge never lag more than a day behind the Gallery.

**Comment by DavidS** [comment]
Comments from puppetize digital

![2020-11-19_19MS+0000_359x295](https://user-images.githubusercontent.com/27712/99716715-5a1e4800-2aa0-11eb-9bd8-afea18ae95d1.png)

**Comment by jordanbreen28** [comment]
closing as work completed - see https://github.com/puppetlabs/Puppet.Dsc/actions/workflows/repuppetize.yml

**Comment by DavidS** [comment]
Thanks a lot @jordanbreen28 !
