### ISSUE TITLE
Add a Logo for the Autogenerated Modules on the Forge

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#70]
Currently the modules on the Forge use the default user logo; a sensible default, such as the PowerShell DSC Community logo, should be used instead.

**Comment by michaeltlombardi** [comment]
CC @binford2k and @gaelcolas

**Comment by gaelcolas** [comment]
Maybe the Puppet logo with the DSC Community logo as overlay?
https://github.com/dsccommunity/dsccommunity.org/blob/master/static/images/DSC_Logo.svg

**Comment by binford2k** [comment]
@gaelcolas what's the license of that image?

**Comment by gaelcolas** [comment]
Yes! :)
Just something I hacked around one day and asked around what people would prefer, so it's open/free.
I've just updated the repo with an MIT license, so the picture in there is also under MIT.
If you'd like something else, let me know.

**Comment by michaeltlombardi** [comment]
Done! Using the DSC Community logo to emphasize that these are auto-generated from the Gallery.

![image](https://user-images.githubusercontent.com/14190564/98391251-06c9e580-201c-11eb-9262-e3516dc45fa6.png)
