### ISSUE TITLE
Automatic Documentation does not appropriately clarify which properties are for Puppet and which are for DSC

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#72]
## Describe the Bug
It is unclear which attributes of a type will be passed to `Invoke-Dsc` and which ones will not.

## Expected Behavior
It should be abundantly clear in the automatic documentation for each module that the only properties and parameters passed along to `Invoke-DscResource` are prepended in the manifest with `dsc_` - any other attributes govern the behavior of Puppet with regard to that resource (for example, in the future when you can distinguish between executing in Windows PowerShell 5.1 or PowerShell 7.2).

## Additional Context
Reported in puppetlabs/ruby-pwsh#52 by @epsilon-jpage

## Acceptance Criteria

- [x] `Get-ReadmeContent` includes a specific sub-section inside of `Usage` which explains that _only_ attributes prepended with `dsc_` will be passed to `Invoke-DscResource` - any other properties are for changing/specifying Puppet behavior, such as metaparameters, title, etc.

**Comment by epsilon-jpage** [comment]
Indeed.
