### ISSUE TITLE
xwebadministration dsc_xiislogging

### ISSUE THREAD

**Issue by epsilon-jpage** [puppetlabs/Puppet.Dsc#73]
## Describe the Bug
When trying to use the dsc_xiislogging class to Add IIS X-Forwarded-For Log File Flag to the IIS Server default it is not working as expecgted..

## Expected Behavior
Custom IIS X-Forwarded-For Log File Flag should be configured to the IIS server.

## Steps to Reproduce
In the Puppetfile I added ...
mod 'dsc-xwebadministration', '3.2.0-0-0'

As per documentation found [here](https://github.com/dsccommunity/xWebAdministration/blob/d66aeeb841c6dad56bf17ba0abffc5ca598c1bbb/tests/Integration/MSFT_XIISLogging.config.ps1), in a test profile I wrote ...
```
  dsc_xiislogging { "Add IIS X-Forwarded-For Log File Flag":
    dsc_ensure => "Present",
    dsc_logcustomfields => "@(
    MSFT_xLogCustomField
      {
        LogFieldName = 'X-Forwarded-For'
        SourceName   = 'X-Forwarded-For'
        SourceType   = 'RequestHeader'
      }
    )",
  }
```

Upon puppet agent -t run ...
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'dsc_ensure' (file: /etc/puppetlabs/code/environments/development/site-modules/profile/manifests/test_webserver_profile.pp, line: 50) on Dsc_xiislogging[Add IIS X-Forwarded-For Log File Flag] (file: /etc/puppetlabs/code/environments/development/site-modules/profile/manifests/test_webserver_profile.pp, line: 50) on node dw-hwke-web01.aws.cloud.epsilon

Warning: Not using cache on failed catalog

Error: Could not retrieve catalog; skipping run

When I try this configuration ...
```
  dsc_xiislogging { "Add IIS X-Forwarded-For Log File Flag":
    dsc_logcustomfields => "@(
    MSFT_xLogCustomField
      {
        LogFieldName = 'X-Forwarded-For'
        SourceName   = 'X-Forwarded-For'
        SourceType   = 'RequestHeader'
      }
    )",
  }
```
I get ...
Error: Could not autoload puppet/type/dsc_xiislogging: Illegal Struct member key type. Expected NotUndef, Optional, String, or Enum. Got: Puppet::Pops::Types::PTypeReferenceType

Error: Failed to apply catalog: Could not autoload puppet/type/dsc_xiislogging: Illegal Struct member key type. Expected NotUndef, Optional, String, or Enum. Got: Puppet::Pops::Types::PTypeReferenceType

When I try this config ...
```
  dsc_xiislogging { "Add IIS X-Forwarded-For Log File Flag":
    ensure => "Present",
    dsc_logcustomfields => "@(
    MSFT_xLogCustomField
      {
        LogFieldName = 'X-Forwarded-For'
        SourceName   = 'X-Forwarded-For'
        SourceType   = 'RequestHeader'
      }
    )",
  }
```
I also get ...
Error: Could not autoload puppet/type/dsc_xiislogging: Illegal Struct member key type. Expected NotUndef, Optional, String, or Enum. Got: Puppet::Pops::Types::PTypeReferenceType

Error: Failed to apply catalog: Could not autoload puppet/type/dsc_xiislogging: Illegal Struct member key type. Expected NotUndef, Optional, String, or Enum. Got: Puppet::Pops::Types::PTypeReferenceType

## Environment
Windows Server 2019.
Puppet Enterprise 2019.8.1
dsc-xwebadministration 3.2.0-0-0

**Comment by michaeltlombardi** [comment]
You have incorrectly specified the `dsc_logcustomfields` property in your manifest. It _looks_ like you copied the example structure from the PowerShell module's documentation, which is how you would do this in the DSC domain specific language (DSL), which is different from the Puppet DSL.

As discussed in puppetlabs/ruby-pwsh#51 [here](https://github.com/puppetlabs/ruby-pwsh/issues/51#issuecomment-715449205):

> `dsc_logcustomfields` has the following type definition:
> 
> ```
> Array[Struct[{ SourceType => Enum['RequestHeader', 'ResponseHeader', 'ServerVariable'], SourceName => String, Ensure => Optional[Enum['Present', 'Absent']], LogFieldName => String }]]
> # Expanded for easier readability
> Array[
>   Struct[{
>     SourceType => Enum['RequestHeader', 'ResponseHeader', 'ServerVariable'],
>     SourceName => String,
>     Ensure => Optional[Enum['Present', 'Absent']],
>     LogFieldName => String
>   }]
> ]
> ```
> 
> which you would represent in a Puppet manifest like so:
> 
> ```puppet
> dsc_logcustomfields => [{
>   SourceType   => 'RequestHeader',
>   SourceName   => 'Foo',
>   LogFieldName => 'Bar',
> }],
> #Example with two custom fields
> dsc_logcustomfields => [
>   {
>     SourceType   => 'RequestHeader',
>     SourceName   => 'Foo',
>     LogFieldName => 'Bar',
>   },
>   {
>     SourceType   => 'ResponseHeader',
>     SourceName   => 'Baz',
>     LogFieldName => 'Qux',
>   }
> ],
> ```

You can find generally the type definition for properties in the reference section of the module on the forge; in this case, the [reference docs for `dsc_logcustomfields`](https://forge.puppet.com/dsc/xwebadministration/reference#dsc_logcustomfields).
