### ISSUE TITLE
Puppetize and Publish PowerShell Modules at the versions last vendored into puppetlabs-dsc

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#89]
## Use Case
Converting from the legacy [`puppetlabs-dsc`] module to the new auto-generated modules should be as smooth as possible, meaning users can swap out their existing implementation _without worrying about changes to the PowerShell code under the DSC modules they currently use_.

## Describe the Solution You Would Like
All of the modules last vendored into the `puppetlabs-dsc` module have been puppetized with `New-PuppetDscModule` and published to the forge.

## Acceptance Criteria

The following PowerShell modules have been puppetized and released to the forge at the version indicated; if that version cannot be found on the gallery, it must be noted and generated at the next released version:

- [x] ActiveDirectoryCSDsc: 3.2.0.0
- [x] AuditPolicyDsc: 1.4.0.0
- [x] CertificateDsc: 4.4.0.0
- [x] ComputerManagementDsc: 6.2.0.0
- [x] DFSDsc: 4.3.0.0
- [x] NetworkingDsc: 7.0.0.0
- [x] OfficeOnlineServerDsc: 1.2.0.0
- [x] SecurityPolicyDsc: 2.7.0.0
- [x] SharePointDsc: 3.2.0.0
- [x] SqlServerDsc: 12.3.0.0
- [x] StorageDsc: 4.5.0.0
- [x] SystemLocaleDsc: 1.2.0.0
- [x] xActiveDirectory: 2.24.0.0
- [x] xAzure: 0.2.0.0
- [x] xAzurePack: 1.4.0.0
- [x] xBitlocker: 1.4.0.0
- [x] xCredSSP: 1.3.0.0
- [x] xDatabase: 1.9.0.0
- [x] xDefender: 0.2.0.0
- [x] xDhcpServer: 2.0.0.0
- [x] xDisk: 1.0
- [x] xDismFeature: 1.3.0.0
- [x] xDnsServer: 1.11.0.0
- [x] xExchange: 1.27.0.0
- [x] xFailOverCluster: 1.12.0.0
- [x] xHyper-V: 3.16.0.0
- [x] xInternetExplorerHomePage: 1.0.0
- [x] xJea: 0.3.0.0
- [x] xMySql: 2.1.0.0
- [x] xPendingReboot: 0.4.0.0
- [x] xPhp: 1.2.0.0 - 
- [x] xPowerShellExecutionPolicy: 3.1.0.0
- [x] xPSDesiredStateConfiguration: 8.5.0.0
- [x] xRemoteDesktopAdmin: 1.1.0.0
- [x] xRemoteDesktopSessionHost: 1.8.0.0
- [x] xRobocopy: 2.0.0.0
- [x] xSCDPM: 1.2.0.0
- [x] xSCOM: 1.3.3.0
- [x] xSCSMA: 2.0.0.0
- [x] xSCSPF: 1.3.1.0
- [x] xSCSR: 1.3.0.0
- [x] xSCVMM: 1.2.4.0
- [x] xSmbShare: 2.1.0.0
- [x] xSqlPs: 1.4.0.0
- [x] xTimeZone: 1.8.0.0
- [x] xWebAdministration: 2.5.0.0
- [x] xWebDeploy: 1.2.0.0
- [x] xWindowsEventForwarding: 1.0.0.0
- [x] xWindowsRestore: 1.0.0
- [x] xWindowsUpdate: 2.7.0.0
- [x] xWinEventLog: 1.2.0.0
- [x] xWordPress: 1.1.0.0

The following modules cannot be automatically puppetized at the same version because they referenced commit SHAs instead of versions discoverable on the gallery; instead release the next stable version after these SHA's and make sure to annotate in #90 that these are close but not precise replacements:

- [x] FileContentDsc: 272086660b16874a400800a76b85ee47e26421e2
- [x] FSRMDsc: 8945f610fa9a6f7f920260abf4e50d91db25bac0
- [x] iSCSIDsc: 2208ad24a0cc0a85ce19fb377e72fbc21d366587
- [x] WmiNamespaceSecurityDsc: d49daa4c18f12aabf32fd60631d927c6d276a453 - puppetized as `dsc/wminamespacesecurity` due to the name of the module changing when pushed to the [PowerShell Gallery](https://www.powershellgallery.com/packages/WmiNamespaceSecurity/0.3.0) vs the old code repository.
- [x] WSManDsc: 1aa6400e7ffa1932505bf9904a7ce9e147af9c45

**Comment by pmcmaw** [comment]
Note: xJea: 0.3.0.0 hasn't been published yet. 
Planning on pinning to 0.2.16-6-0 as it was released 5/14/2015 on the Gallery.
